name:                vkpure
version:             0.1.0.0
github:              "githubuser/vkpure"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- OverloadedLabels
- AllowAmbiguousTypes
- ApplicativeDo
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
- QuasiQuotes
- NoImplicitPrelude

# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vkpure#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- array
- bytestring
- lens
- generic-lens
- servant
- servant-client
- servant-client-core
- servant-multipart
- servant-multipart-client
- servant-multipart-api
- template-haskell
- text
- transformers
- transformers-either
- http-client
- http-client-tls
- named

library:
  source-dirs: src

executables:
  vkpure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vkpure

tests:
  vkpure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vkpure
